scales:
    diatonic:
        intervals: '2212221'
        modes: 
            - ionian
            - dorian
            - phyrigian
            - lydian
            - mixolydian
            - aeolian
            - locrian
    chromatic: 
        intervals: '111111111111'
    wholetone:
        human: 'whole tone'
        intervals: '222222'
    bebop: 
        intervals: '2212p121'
    pentatonic: 
        intervals: '23223'
        modes:
            - yo
            - minorpentatonic
            - majorpentatonic
            - egyption
            - mangong
    blues: 
        intervals: '32p132'
    melodicminor: 
        intervals: '2122221'
    harmonicminor: 
        human: 'harmonic minor'
        intervals: '2122132'
        modes:
            - harmonicminor
            - locriann6
            - ionianaug#5
            - dorian#4
            - phyrigianminor
            - lydian#9
            - alteredbb7
    harmonicmajor:
        human: 'harmonic major'
        intervals: '2122132'
        modes:
            - dorianb5
            - phyrgianb4
            - lydianb3
            - mixolydianb2
            - lydianaug#2
            - locrianbb7
    doubleharmonic:
        human: 'double harmonic'
        intervals: '1312131'
        modes:
            - doubleharmonic
            - lydian#2#6
            - ultraphyrigian
            - hungarianminor
            - oriental
            - ionianaug
            - locrianbb3bb7
    neapolitan:
        intervals: '1222221'
        modes:
            - neapolitan
            - leadingwholetone
            - lydianaugdom
            - minorlydian
            - arabian
            - semilocrianb4
            - superlocrianbb3
    neapolitanminor:
        human: 'neapolitan minor'
        intervals: '222222'
        modes:
            - neapolitanminor
            - lydian#6
            - mixolydianaug
            - hungarian
            - locriandom
            - ionain#2
            - ultralocrianbb3

chords:
    '1': ''
    '#1': '#1'
    ':#2': '#1'
    ':b2': 'b2'
    ':2': '2'
    ':#2': '#2'
    ':b3': 'b3'
    ':3': '3'
    ':4': '4'
    ':#4': '#4'
    ':b5': 'b5'
    ':5': '5'
    ':#5': '#5'
    ':b6': 'b6'
    ':6': '6'
    ':#6': '#6'
    ':b7': 'b7'
    ':7': '7'
    ':8': '8'
    '2': '2'
    '#2': '#2'
    b3: 'b3'
    '3': '3'
    '4': '4'
    '#4': '#4'
    b5: 'b5'
    '5': '5'
    '#5': '#5'
    b6: 'b6'
    '#6': '#6'
    p7: '7'
    b7: 'b7'
    '8': '8'
    #9: '#9'
    # '#11: '#11' # easy confusion with 11 chord

    # Common chords and voicings

    ma: '3 5'
    mab5: '3 b5' # lyd
    ma#4: '3 #4 5' # lydadd5
    ma6: '3 5 6'
    ma69: '3 5 6 9'
    ma769: '3 5 6 7 9'
    m69: 'b3 5 6 9'
    ma7: '3 5 7'
    ma7#4: '3 #4 5 7' # lyd7add5
    ma7b5: '3 b5 7' # lyd7
    ma7b9: '3 5 7 b9'
    ma7b13: '3 5 7 9 11 b13'
    ma9: '3 5 7 9'
    # 'maadd9: '3 5 9'
    ma9b5: '3 b5 7 9'
    ma9+: '3 #5 7 9'
    ma#11: '3 b5 7 9 #11'
    ma11: '3 5 7 9 11'
    ma11b5: '3 b5 7 9 11'
    ma11+: '3 #5 7 9 11'
    ma11b13: '3 #5 7 9 11 b13'
    # 'maadd11: '3 5 11'
    # 'maadd#11: '3 5 #11'
    ma13: '3 5 7 9 11 13'
    ma13b5: '3 b5 7 9 11 13'
    ma13+: '3 #5 7 9 11 13'
    ma13#4: '3 #4 5 7 9 11 13'
    m: 'b3 5'
    m6: 'b3 5 6'
    m7: 'b3 5 b7'
    m69: 'b3 5 6 9'
    m769: 'b3 5 6 7 9'
    # 'madd9: '3 b5 9'
    m7b5: 'b3 b5 b7'
    m7+: 'b3 #5 b7'
    m9: 'b3 5 b7 9'
    m9+: 'b3 #5 b7 9'
    m11: 'b3 5 b7 9 11'
    m11+: 'b3 #5 b7 9 11'
    m11b9: 'b3 5 b7 b9 11'
    m11b13: 'b3 5 b7 9 11 b13'
    m13: 'b3 5 b7 9 11 13'
    m13b9: '3 5 b7 b9 11 13'
    m13#9: '3 5 b7 #9 11 13'
    m13b11: '3 5 b7 #9 b11 13'
    m13#11: '3 5 b7 #9 #11 13'
    +: '3 #5'
    7+: '3 #5 b7'
    9+: '3 #5 b7 9'
    11+: '3 #5 b7 9 11'
    13+: '3 #5 b7 9 11 13'
    'ma6': '3 5 6'
    'ma11': '3 5 b7 9 #11'
    'ma13': '3 5 7 9 11 13'
    'ma15': '3 5 b7 9 #11 #15'
    '7': '3 5 b7'
    7b5: '3 b5 b7'
    '69': '3 5 6 b7 9'
    7+: '3 #5 b7'
    7b9: '3 5 b7 b9'
    '9': '3 5 b7 9'
    9b5: '3 b5 b7 9'
    9+: '3 #5 b7 9'
    '9#11': '3 5 b7 9 #11'
    '11': '3 5 b7 9 11'
    11b5: '3 b5 b7 9 11'
    11+: '3 #5 b7 9 11'
    11b9: '3 5 b7 b9 11'
    '6': '3 5 6'
    '9': '3 5 b7 9'
    '11': '3 5 b7 9 #11'
    '13': '3 5 b7 9 11 13'
    13b5: '3 b5 b7 9 11 13'
    13#11: '3 5 b7 9 #11 13'
    13+: '3 #5 b7 9 13'
    '15': '3 5 b7 9 #11 #15'
    dim: 'b3 b5'
    dim7: 'b3 b5 bb7'
    dim9: 'b3 b5 bb7 9'
    dim11: 'b3 b5 bb7 9 11'
    sus: '4 5'
    sus2: '2 5'

    pow: '5 8'

chord_alts:
    r: '1'
    #M2: '2'
    #M3: '3'
    aug: +
    aug7: '7+'
    ma#5: +
    p4: '4'
    p5: '5'
    -: m
    M: ma
    sus4: sus
    # major: maj
    ma7: ma7
    ma9: ma9
    lyd: mab5
    lyd7: ma7b5
    plyd: ma#4
    lyd5: ma#4
    # Madd9: maadd9
    # maor7: ma7
    # Mb5: mab5
    # M7: ma7
    # M7b5: ma7b5
    # min: m
    # minor: m
    # min7: m7
    # minor7: m7
    p: pow
    o: dim
    o7: dim7
    7o: dim7
    o9: dim9
    9o: dim9
    o11: dim11
    11o: dim11
    # mma7: mm7
    # mma9: mm9
    # mma11: mm11
    # mma13: mm13

